import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: scale(17),
    marginVertical: verticalScale(-200),
    paddingVertical: verticalScale(210),
  },
  body: {
    fontSize: moderateScale(32),
    color: "white",
    textAlign: "left",
    marginTop: verticalScale(4),
    fontFamily: "inter-regular",
    marginHorizontal: scale(15),
    letterSpacing: scale(1),
    lineHeight: verticalScale(45),
  },
  card: {
    backgroundColor: "transparent",
    borderRadius: moderateScale(10),
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#fff",
    padding: scale(23),
    marginVertical: verticalScale(30),
    width: "92%",
    alignItems: "flex-start",
  },
  cardTitle: {
    fontSize: moderateScale(25),
    marginBottom: verticalScale(40),
    color: "white",
    fontFamily: "inter-light",
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    color: "white",
  },
  checkbox: {
    width: scale(24),
    height: scale(24),
    borderWidth: 1,
    borderColor: "#fff",
    left: scale(10),
  },
  label: {
    fontSize: moderateScale(26),
    color: "white",
    marginHorizontal: scale(20),
    fontFamily: "inter-light",
    lineHeight: verticalScale(45),
  },
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flexGrow: 1,
    justifyContent: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: verticalScale(1),
    paddingVertical: verticalScale(26),
    paddingHorizontal: scale(20),
    borderRadius: moderateScale(5),
  },
  textContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginTop: verticalScale(30),
  },
  greeting: {
    fontSize: moderateScale(24),
    color: "#ffff",
    fontFamily: "inter-medium",
  },
  userName: {
    fontSize: moderateScale(24),
    color: "#FFFFF",
    fontFamily: "inter-bold",
  },
  location: {
    fontSize: moderateScale(18),
    color: "#FFFFFF",
    marginTop: verticalScale(5),
  },
  icon: {
    width: scale(60),
    height: scale(60),
    marginTop: verticalScale(35),
  },
  texthead: {
    marginTop: verticalScale(40),
    fontSize: moderateScale(23),
    fontFamily: "inter-bold",
    color: "#FFFFF",
  },
  textbox: {
    width: scale(300),
    height: verticalScale(60),
    marginTop: verticalScale(100),
    marginVertical: verticalScale(20),
    justifyContent: "center",
    backgroundColor: "transparent",
    color: "#FFFFFF",
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(20),
  },
  textboxI: {
    width: scale(300),
    height: verticalScale(60),
    marginTop: verticalScale(1),
    marginVertical: verticalScale(20),
    justifyContent: "center",
    backgroundColor: "transparent",
    color: "#FFFFF",
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(20),
  },
  textboxII: {
    width: scale(300),
    height: verticalScale(60),
    marginTop: verticalScale(1),
    marginVertical: verticalScale(20),
    justifyContent: "center",
    backgroundColor: "transparent",
    color: "#FFFFF",
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(20),
  },
  textboxIII: {
    width: scale(120),
    height: verticalScale(60),
    marginTop: verticalScale(5),
    backgroundColor: "transparent",
    color: "#FFFFF",
    marginLeft: scale(-180),
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(20),
  },
  textboxIV: {
    width: scale(120),
    height: verticalScale(60),
    marginTop: verticalScale(-80),
    backgroundColor: "transparent",
    color: "#FFFFF",
    marginLeft: scale(170),
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
  },
  textboxV: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    color: "white",
  },
  button3: {
    width: scale(50),
    height: scale(50),
    borderRadius: scale(25),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(-40),
    marginBottom: verticalScale(40),
    marginLeft: scale(200),
  },
  input: {
    width: "100%",
    height: verticalScale(40),
    borderColor: "#fff",
    borderWidth: 1,
    borderRadius: moderateScale(5),
    paddingHorizontal: scale(10),
    color: "white",
    marginBottom: verticalScale(20),
    backgroundColor: "transparent",
  },
});

export default styles;
