import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";

export default StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: scale(30),
  },
  title: {
    marginTop: verticalScale(30),
    fontSize: moderateScale(24),
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: verticalScale(10),
    textAlign: "center",
  },
  resultContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  pdfButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0A4E66",
    paddingVertical: verticalScale(40),
    paddingHorizontal: scale(20),
    borderRadius: moderateScale(10),
    marginVertical: verticalScale(10),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: verticalScale(5) },
    shadowOpacity: 0.3,
    shadowRadius: moderateScale(10),
    elevation: 5,
  },
  pdfButtonText: {
    color: "#FFFFFF",
    fontSize: moderateScale(18),
    fontWeight: "bold",
    marginLeft: scale(10),
  },
  appButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#119797",
    paddingVertical: verticalScale(40),
    paddingHorizontal: scale(20),
    borderRadius: moderateScale(10),
    marginVertical: verticalScale(30),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: verticalScale(5) },
    shadowOpacity: 0.3,
    shadowRadius: moderateScale(10),
    elevation: 5,
  },
  appButtonText: {
    color: "#FFFFFF",
    fontSize: moderateScale(18),
    fontWeight: "bold",
    marginLeft: scale(10),
  },
  pdfButtonText2: {
    color: "#FFFFFF",
    fontSize: moderateScale(20),
    marginLeft: scale(10),
    marginTop: verticalScale(5),
  },
  respostaItem: {
    backgroundColor: "#032D45",
    padding: scale(10),
    marginBottom: verticalScale(10),
    borderRadius: moderateScale(8),
  },
  respostaText: {
    fontSize: moderateScale(20),
    marginTop: verticalScale(15),
    color: "#D8EBF2",
  },
  noRespostas: {
    color: "#D8EBF2",
    fontSize: moderateScale(18),
    textAlign: "center",
  },
  labelText: {
    color: "#14E2C3",
    fontWeight: "bold",
  },
  text: {
    color: "#FFFFF",
  },
  buttonSearch: {
    width: "70%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0A4E66",
    borderWidth: moderateScale(3),
    borderColor: "#032D45",
    paddingVertical: verticalScale(17),
    paddingHorizontal: scale(15),
    borderRadius: moderateScale(10),
    marginTop: verticalScale(10),
    zIndex: 1000,
  },
  space: {
    marginRight: scale(260),
  },
  notice: {
    backgroundColor: "#032D45",
    marginTop: verticalScale(30),
    padding: scale(5),
    borderRadius: moderateScale(10),
    textAlign: "center",
    fontSize: moderateScale(16),
    fontWeight: "bold",
    color: "#D8EBF2",
    marginBottom: verticalScale(4),
  },
  classificacaoText: {
    fontSize: moderateScale(28),
    fontWeight: "bold",
    color: "#FFFFFF",
    backgroundColor: "#0A4E66",
    paddingVertical: verticalScale(15),
    paddingHorizontal: scale(20),
    borderRadius: moderateScale(0),
    borderWidth: moderateScale(2),
    borderColor: "#0A4E66",
    textAlign: "center",
    marginVertical: verticalScale(20),
    shadowColor: "#14E2C3",
    shadowOffset: { width: 0, height: verticalScale(0) },
    shadowOpacity: 0.8,
    shadowRadius: moderateScale(8),
    elevation: 10,
  },
});
