import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
  },
  container3: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    marginVertical: verticalScale(-150),
    paddingVertical: verticalScale(150),
  },
  clock: {
    marginTop: verticalScale(60),
  },
  home: {
    marginTop: verticalScale(25),
  },
  textXII: {
    fontSize: moderateScale(32),
    color: "white",
    textAlign: "left",
    marginTop: verticalScale(10),
    fontFamily: "inter-regular",
    marginHorizontal: scale(25),
    lineHeight: verticalScale(50),
  },
  textXIII: {
    fontSize: moderateScale(30),
    fontFamily: "inter-bold",
    color: "#FFFF",
    marginBottom: verticalScale(-50),
    marginTop: verticalScale(50),
  },
  textXIV: {
    fontSize: moderateScale(30),
    color: "white",
    textAlign: "left",
    marginTop: verticalScale(70),
    fontFamily: "inter-regular",
    marginHorizontal: scale(25),
    marginVertical: verticalScale(20),
    lineHeight: verticalScale(45),
  },
  textXIV1: {
    fontSize: moderateScale(30),
    color: "white",
    textAlign: "left",
    marginTop: verticalScale(70),
    fontFamily: "inter-regular",
    marginHorizontal: scale(25),
    marginVertical: verticalScale(20),
    lineHeight: verticalScale(45),
  },
  textXV: {
    fontSize: moderateScale(30),
    color: "white",
    textAlign: "left",
    marginTop: verticalScale(20),
    fontFamily: "inter-regular",
    marginHorizontal: scale(25),
    lineHeight: verticalScale(45),
  },
  view3: {
    marginTop: verticalScale(25),
  },
  line: {
    width: scale(140),
    height: verticalScale(3),
    backgroundColor: "white",
    marginTop: verticalScale(50),
    marginBottom: verticalScale(40),
  },
  button: {
    width: scale(50),
    height: scale(50),
    borderRadius: scale(25),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(50),
    marginBottom: verticalScale(30),
    marginLeft: scale(280),
  },
  button3: {
    width: scale(50),
    height: scale(50),
    borderRadius: scale(25),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(20),
    marginBottom: verticalScale(40),
    marginLeft: scale(250),
  },
});
